---
spring:
  datasource:
    password: 123456
    minIdle: 1
    initialSize: 1
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro
    maxActive: 20
    username: root
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  mvc:
    favicon:
      enabled: false
  redis:
      host: localhost
      port: 6379
      database: 5
      password:
      timeout: 0
      jedis:
        pool:
          max-active: 1024
          max-idle: 200
          max-wait: 10000
debug: true
pagehelper:
  supportMethodsArguments: true
  reasonable: true
  helperDialect: mysql
  params: count=countSql
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jiuhong.model
logging:
  level:
    com:
      study: trace
    org:
      springframework:
        web: DEBUG
    tk:
      mybatis: TRACE
mapper:
  identity: MYSQL
  not-empty: false
  mappers: com.jiuhong.util.BaseMapper
